### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Shinoda492039** [Shinoda492039/chat-space#9]
# IPアドレス
52.194.175.163

**Comment by mo1015** [comment]
篠田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○リロードすると、投稿の日付部分の表示崩れがある**
<img width="713" alt="修正" src="https://user-images.githubusercontent.com/62644781/80273772-1a60cf00-8710-11ea-9263-a2fc6c1508d4.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Shinoda492039** [comment]
ご確認ありがとうございます。
修正しました。

**Comment by chiii220** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by Shinoda492039** [comment]
承知しました。
ご確認ありがとうございました。
